language: c
# xenial 16.04
dist: xenial
before_install:
    # For MPI
    - test -n $CC && unset CC
    # Install Lustre
    # TODO: As far as a i can see it needs to be compiled form source with kernel
    # module as there is no package.
    # It seams that there are .debs releases for lustre, but its only for 16.04
    # So need to wait till travis is updated.
    # https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/
    - wget https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/ubuntu1604/client/lustre-client-modules-4.4.0-131-generic_2.10.6-1_amd64.deb
    - wget https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/ubuntu1604/client/lustre-dev_2.10.6-1_amd64.deb
    - wget https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/ubuntu1604/client/lustre-utils_2.10.6-1_amd64.deb
    - wget https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/ubuntu1604/client/lustre-source_2.10.6-1_all.deb
    - wget https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/ubuntu1604/client/lustre-iokit_2.10.6-1_amd64.deb
    - wget https://downloads.whamcloud.com/public/lustre/lustre-2.10.6/ubuntu1604/client/lustre-tests_2.10.6-1_amd64.deb
    - sudo apt-get install -y libsnmp30
    - sudo dpkg -i lustre-client-modules-4.4.0-131-generic_2.10.6-1_amd64.deb lustre-utils_2.10.6-1_amd64.deb lustre-dev_2.10.6-1_amd64.deb lustre-source_2.10.6-1_all.deb lustre-iokit_2.10.6-1_amd64.deb lustre-tests_2.10.6-1_amd64.deb
install:
    - sudo apt-get -qq update
    # Install MPI ---------------------
    - sudo apt-get install -y openmpi-bin libopenmpi-dev
    # Install HDF5 --------------------
    - sudo apt-get install -y hdf5-tools libhdf5-mpi-dev
    # Install  Parallel netcdf --------
    # TODO: Not in repos for 14.04 trustz but comes 16.04 xenial
    - sudo apt-get install -y libpnetcdf-dev pnetcdf-bin
    # Install HDFS --------------------
    # TODO: Not sure with which c libray hdfs should be used and if it is in
    # the ubuntu repos
    # Probably hadoop needs to be installed an provides nativ api.
    # Install Amazon S3 ---------------
    # TODO: The needed library needs to be installed. Follow the instructions in
    # aiori-S3.c to achive this.
    # GPFS ----------------------------
    # NOTE: GPFS seams to need a license and is therefore not testable with travis.
script: ./travis-build.sh && CONFIGURE_OPTS="--with-lustre" ./travis-test.sh
